task : audio_finetuning
w2l_decoder : viterbi
gen_subset : test 
max_tokens : 4000000
beam : 70
beam_size_token : 100
batch_size : 1
skip_invalid_size_inputs_valid_test : True
required_batch_size_multiple : 1
num_shards : 1
shard_id : 0
num_workers : 0
data_buffer_size : 10
cpu : False
fp16 : True
log_format : json
log_interval : 200
prefix_size : 0
no_beamable_mm : False
print_alignment : False
nbest : 1
labels : ltr
beam_threshold : 25.0
lm_weight : 2.0
word_score : -1
sil_weight : 0
unk_weight : -.inf
criterion_type : ctc
model : checkpoint_best.pt
device : cuda